import { useEffect, useState } from 'react';
import { Trash2, UserCheck, X } from 'lucide-react';
import { apiFetch } from '../../api';
import { DismissibleBanner } from '../shared/UXHelpers';
import AddFieldModal from './AddFieldModal';
import { CompletionPolicy, DeadlinePicker, PanelFrame, SearchDropdown, SectionLabel } from './StepPanelShared';

const DEFAULTS={assignmentTargetType:'USER',actorUserIds:[],assignmentGroupIds:[],completionMode:'ANY',completionPercentage:50,deadlineHours:24,deadlineDate:null};

export default function AssignmentStepPanel({workflowId,step,onClose,onDelete}){
 const [config,setConfig]=useState(DEFAULTS),[users,setUsers]=useState([]),[groups,setGroups]=useState([]),[fields,setFields]=useState([]),[query,setQuery]=useState(''),[modal,setModal]=useState(false),[editingField,setEditingField]=useState(null),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/config`).then(json),apiFetch('/api/users/active').then(json),apiFetch('/api/groups').then(json),apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/fields`).then(json)]).then(([c,u,g,f])=>{setConfig({...DEFAULTS,...c});setUsers(Array.isArray(u)?u:[]);setGroups(Array.isArray(g)?g:[]);setFields(Array.isArray(f)?f:[])}).catch(e=>setMessage(e.message));},[workflowId,step.id]);
 const userMode=config.assignmentTargetType==='USER';
 const selected=userMode?users.filter(u=>config.actorUserIds?.includes(u.id)):groups.filter(g=>config.assignmentGroupIds?.includes(g.id));
 const items=(userMode?users:groups).filter(x=>!(userMode?config.actorUserIds:config.assignmentGroupIds)?.includes(x.id)).map(x=>({id:x.id,value:x.id,label:userMode?x.displayName:x.name,description:userMode?`${x.email} · ${x.jobTitle||'Chưa có chức danh'}`:`${x.memberCount||0} thành viên`}));
 const choose=item=>{setConfig(c=>userMode?{...c,actorUserIds:[...(c.actorUserIds||[]),item.id]}:{...c,assignmentGroupIds:[...(c.assignmentGroupIds||[]),item.id]});setQuery('')};
 const remove=id=>setConfig(c=>userMode?{...c,actorUserIds:c.actorUserIds.filter(x=>x!==id)}:{...c,assignmentGroupIds:c.assignmentGroupIds.filter(x=>x!==id)});
 const save=async()=>{setSaving(true);const r=await apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/config/assignment`,{method:'PUT',body:JSON.stringify(config)});setMessage(r.ok?'Đã lưu cấu hình Assignment Step.':await error(r));setSaving(false)};
 const addField=async data=>{const r=await apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/fields${editingField?`/${editingField.id}`:''}`,{method:editingField?'PUT':'POST',body:JSON.stringify(data)});if(r.ok){const saved=await r.json();setFields(v=>editingField?v.map(f=>f.id===saved.id?saved:f):[...v,saved]);setEditingField(null);setModal(false)}else setMessage(await error(r))};
 const deleteField=async id=>{const r=await apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/fields/${id}`,{method:'DELETE'});if(r.ok)setFields(v=>v.filter(f=>f.id!==id));else setMessage(await error(r))};
 return <PanelFrame icon={UserCheck} title="Cấu hình: Assignment Step" onClose={onClose} onDelete={onDelete} footer={<div className="flex justify-end gap-3"><button onClick={onClose} className="rounded-lg border border-grayBorder px-5 py-2 text-xs font-medium">Hủy</button><button onClick={save} disabled={saving} className="btn-primary px-5 py-2 text-xs disabled:opacity-60">{saving?'Đang lưu...':'Lưu cấu hình'}</button></div>}>
  <div className="space-y-6">
   <section><SectionLabel>Giao việc cho</SectionLabel><div className="mb-3 flex gap-4 border-b text-xs font-medium"><button onClick={()=>{setConfig(c=>({...c,assignmentTargetType:'USER'}));setQuery('')}} className={`pb-2 ${userMode?'border-b-2 border-orange-500 text-orange-600':'text-gray-500'}`}>User cụ thể</button><button onClick={()=>{setConfig(c=>({...c,assignmentTargetType:'GROUP'}));setQuery('')}} className={`pb-2 ${!userMode?'border-b-2 border-orange-500 text-orange-600':'text-gray-500'}`}>Nhóm người thực hiện</button></div>{!userMode&&<DismissibleBanner storageKey="wf_banner_group_info" className="mb-3">Group là danh sách User do Admin quản lý tại <b>Cài đặt hệ thống → Nhóm người thực hiện</b>. Khi step được kích hoạt, mỗi thành viên active trong Group sẽ nhận một task.</DismissibleBanner>}<p className="mb-1.5 text-[11px] text-gray-500">Chọn {userMode?'người':'nhóm'} thực hiện</p><div className="mb-2 flex flex-wrap gap-1.5">{selected.map(x=><span key={x.id} className="flex items-center gap-1 rounded-full bg-orange-50 px-2.5 py-1 text-[10px] text-orange-700">{userMode?x.displayName:x.name}<button onClick={()=>remove(x.id)}><X size={11}/></button></span>)}</div><SearchDropdown value={query} onInput={setQuery} onSelect={choose} items={items} placeholder={userMode?'Tìm người thực hiện...':'Tìm nhóm người thực hiện...'}/></section>
   <CompletionPolicy config={config} setConfig={setConfig}/>
   <DeadlinePicker config={config} setConfig={setConfig}/>
   <section><SectionLabel>Custom Input Fields (Yêu cầu nhập liệu)</SectionLabel><div className="space-y-2">{fields.map(f=><div key={f.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"><div><p className="text-xs font-semibold">{f.label}</p><p className="text-[10px] text-gray-400">{f.fieldKey} | {f.type}</p></div><div className="flex items-center gap-2"><span className={`text-[10px] ${f.required?'text-orange-500':'text-gray-400'}`}>{f.required?'Bắt buộc':'Tùy chọn'}</span><button onClick={()=>{setEditingField(f);setModal(true)}} className="text-[10px] font-semibold text-orange-500">Sửa</button><button onClick={()=>deleteField(f.id)} className="text-gray-400 hover:text-red-500"><Trash2 size={13}/></button></div></div>)}<button onClick={()=>{setEditingField(null);setModal(true)}} className="w-full rounded-lg border border-dashed border-orange-400 py-2 text-xs font-medium text-orange-500 hover:bg-orange-50">+ &nbsp;Thêm field</button></div></section>
   {message&&<p className={`rounded-lg px-3 py-2 text-xs ${message.startsWith('Đã')?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-600'}`}>{message}</p>}
  </div><AddFieldModal isOpen={modal} onClose={()=>{setModal(false);setEditingField(null)}} onSave={addField} editingField={editingField}/>
 </PanelFrame>;
}
async function json(r){if(!r.ok)throw new Error(await error(r));return r.json()}async function error(r){const b=await r.json().catch(()=>null);return b?.message||'Không thể lưu cấu hình';}
