import { useEffect, useState } from 'react';
import { Bell, Database, Globe2, Plus, PlusCircle, RefreshCw, Settings2, Trash2 } from 'lucide-react';
import { apiFetch } from '../../api';
import { PanelFrame, SectionLabel } from './StepPanelShared';

const DEFAULTS={actionType:'API_CALL',endpointUrl:'',httpMethod:'POST',payloadTemplate:'{\n  "requestCode": "{{requestCode}}"\n}',notificationChannel:'IN_APP',notificationTitle:'Thông báo workflow',notificationBody:'Yêu cầu {{requestCode}} đã được xử lý.',webhookUrl:'',targetType:'REQUEST',recordType:'',newStatus:'COMPLETED',mappings:[],failurePolicy:'STOP',retryCount:3,timeoutSeconds:30};
const ACTIONS=[
 ['API_CALL','Gọi API ngoài',Globe2],['SEND_NOTIFICATION','Gửi thông báo',Bell],['UPDATE_DATA','Cập nhật dữ liệu',Database],
 ['CREATE_RECORD','Tạo record mới',PlusCircle],['UPDATE_STATUS','Cập nhật trạng thái',RefreshCw]
];

export default function SystemActionStepPanel({workflowId,step,onClose,onDelete}){
 const [config,setConfig]=useState(DEFAULTS),[fields,setFields]=useState([]),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{Promise.all([load(`/api/workflows/${workflowId}/steps/${step.id}/config`),load(`/api/workflows/${workflowId}/fields`)]).then(([saved,items])=>{setConfig({...DEFAULTS,...saved,mappings:Array.isArray(saved?.mappings)?saved.mappings:[]});setFields(Array.isArray(items)?items:[])}).catch(e=>setMessage(e.message));},[workflowId,step.id]);
 const addMapping=()=>setConfig(c=>({...c,mappings:[...c.mappings,{sourceFieldKey:fields[0]?.fieldKey||'',targetField:c.actionType==='UPDATE_DATA'?(fields[0]?.fieldKey||''):'',valueTemplate:''}]}));
 const updateMapping=(index,key,value)=>setConfig(c=>({...c,mappings:c.mappings.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const removeMapping=index=>setConfig(c=>({...c,mappings:c.mappings.filter((_,i)=>i!==index)}));
 const save=async()=>{setSaving(true);setMessage('');try{const response=await apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/config/system-action`,{method:'PUT',body:JSON.stringify(config)});if(!response.ok)throw new Error(await error(response));setConfig({...DEFAULTS,...await response.json()});setMessage('Đã lưu cấu hình System Action Step.')}catch(e){setMessage(e.message)}finally{setSaving(false)}};
 return <PanelFrame icon={Settings2} title="Cấu hình: System Action Step" subtitle="Thiết lập tác vụ tự động của hệ thống" onClose={onClose} onDelete={onDelete} footer={<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-grayBorder px-4 py-2.5 text-sm text-slate-600">Hủy</button><button type="button" onClick={save} disabled={saving} className="btn-primary min-w-[150px] py-2.5 text-sm disabled:opacity-60">{saving?'Đang lưu...':'Lưu cấu hình'}</button></div>}>
  <div className="space-y-6">
   <section><SectionLabel>Loại hành động</SectionLabel><div className="grid grid-cols-3 gap-2">{ACTIONS.map(([value,label,Icon])=><button key={value} type="button" onClick={()=>setConfig(c=>({...c,actionType:value,mappings:[]}))} className={`flex min-h-[78px] flex-col items-center justify-center gap-2 rounded-lg border px-2 py-3 text-[11px] font-semibold transition ${config.actionType===value?'border-orange-500 bg-orange-50 text-orange-600':'border-grayBorder bg-white text-slate-600 hover:border-orange-200'}`}><Icon size={18}/><span className="text-center">{label}</span></button>)}</div></section>

   <section><SectionLabel>Chi tiết cấu hình</SectionLabel>
    {config.actionType==='API_CALL'&&<div className="space-y-4"><Field label="Endpoint URL *"><input value={config.endpointUrl} onChange={e=>setConfig(c=>({...c,endpointUrl:e.target.value}))} className="input-field" placeholder="https://api.example.com/orders"/></Field><Field label="Method"><select value={config.httpMethod} onChange={e=>setConfig(c=>({...c,httpMethod:e.target.value}))} className="input-field bg-white"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></Field><Field label="Payload (JSON)"><textarea rows={5} value={config.payloadTemplate} onChange={e=>setConfig(c=>({...c,payloadTemplate:e.target.value}))} className="input-field resize-y font-mono text-xs"/></Field></div>}
    {config.actionType==='SEND_NOTIFICATION'&&<div className="space-y-4"><Field label="Kênh thông báo"><select value={config.notificationChannel} onChange={e=>setConfig(c=>({...c,notificationChannel:e.target.value}))} className="input-field bg-white"><option value="IN_APP">In-app Notification</option><option value="EMAIL">Email</option><option value="TEAMS">Teams</option><option value="WEBHOOK">Webhook</option></select></Field>{config.notificationChannel==='WEBHOOK'&&<Field label="Webhook URL"><input value={config.webhookUrl||''} onChange={e=>setConfig(c=>({...c,webhookUrl:e.target.value}))} className="input-field" placeholder="https://api.example.com/webhook"/></Field>}<Field label="Tiêu đề"><input value={config.notificationTitle} onChange={e=>setConfig(c=>({...c,notificationTitle:e.target.value}))} className="input-field"/></Field><Field label="Nội dung"><textarea rows={5} value={config.notificationBody} onChange={e=>setConfig(c=>({...c,notificationBody:e.target.value}))} className="input-field resize-y"/><p className="mt-1 text-[10px] text-gray-400">Có thể dùng {'{{requestCode}}'}, {'{{workflowName}}'} và field của workflow.</p></Field></div>}
    {config.actionType==='UPDATE_DATA'&&<Field label="Đối tượng dữ liệu"><select value={config.targetType} onChange={e=>setConfig(c=>({...c,targetType:e.target.value}))} className="input-field bg-white"><option value="REQUEST">Request hiện tại</option></select></Field>}
    {config.actionType==='CREATE_RECORD'&&<Field label="Loại record"><input value={config.recordType} onChange={e=>setConfig(c=>({...c,recordType:e.target.value}))} className="input-field" placeholder="Purchase Order"/></Field>}
    {config.actionType==='UPDATE_STATUS'&&<div className="space-y-4"><Field label="Đối tượng"><select value={config.targetType} onChange={e=>setConfig(c=>({...c,targetType:e.target.value}))} className="input-field bg-white"><option value="REQUEST">Request hiện tại</option></select></Field><Field label="Trạng thái mới"><select value={config.newStatus} onChange={e=>setConfig(c=>({...c,newStatus:e.target.value}))} className="input-field bg-white"><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option><option value="REJECTED">Rejected</option><option value="CANCELLED">Cancelled</option></select></Field></div>}
   </section>

   {['API_CALL','UPDATE_DATA','CREATE_RECORD'].includes(config.actionType)&&<section><SectionLabel>Mapping dữ liệu</SectionLabel><div className="overflow-hidden rounded-lg border border-grayBorder"><div className="grid grid-cols-[1fr_1fr_36px] bg-slate-50 px-3 py-2 text-[10px] font-bold uppercase text-slate-500"><span>Field hệ thống</span><span>{config.actionType==='UPDATE_DATA'?'Field cần cập nhật':'Field đích'}</span><span/></div>{config.mappings.map((mapping,index)=><div key={index} className="grid grid-cols-[1fr_1fr_36px] items-center gap-2 border-t border-slate-100 px-3 py-2"><select value={mapping.sourceFieldKey||''} onChange={e=>updateMapping(index,'sourceFieldKey',e.target.value)} className="rounded-md border border-grayBorder bg-white px-2 py-2 text-xs"><option value="">Giá trị tùy chỉnh</option>{fields.map(field=><option key={field.fieldKey} value={field.fieldKey}>{field.label}</option>)}</select>{config.actionType==='UPDATE_DATA'?<select value={mapping.targetField||''} onChange={e=>updateMapping(index,'targetField',e.target.value)} className="rounded-md border border-grayBorder bg-white px-2 py-2 text-xs"><option value="">Chọn field</option>{fields.map(field=><option key={field.fieldKey} value={field.fieldKey}>{field.label}</option>)}</select>:<input value={mapping.targetField||''} onChange={e=>updateMapping(index,'targetField',e.target.value)} className="rounded-md border border-grayBorder px-2 py-2 text-xs" placeholder="amount"/>}<button type="button" onClick={()=>removeMapping(index)} className="text-gray-400 hover:text-red-500"><Trash2 size={15}/></button>{!mapping.sourceFieldKey&&<input value={mapping.valueTemplate||''} onChange={e=>updateMapping(index,'valueTemplate',e.target.value)} className="col-span-2 rounded-md border border-grayBorder px-2 py-2 text-xs" placeholder="Giá trị hoặc {{fieldKey}}"/>}</div>)}</div><button type="button" onClick={addMapping} className="mt-2 flex w-full items-center justify-center gap-1 rounded-lg border border-dashed border-grayBorder py-2.5 text-xs font-medium text-slate-500 hover:border-orange-300 hover:text-orange-500"><Plus size={14}/> Thêm mapping</button>{!fields.length&&<p className="mt-2 text-xs text-amber-600">Workflow chưa có field form để mapping.</p>}</section>}

   <section className="border-t border-grayBorder pt-5"><SectionLabel>Xử lý khi lỗi</SectionLabel><div className="space-y-3 text-xs text-slate-700">{[['STOP','Dừng workflow và báo lỗi'],['CONTINUE','Bỏ qua và tiếp tục'],['RETRY','Thử lại']].map(([value,label])=><label key={value} className="flex items-center gap-2"><input type="radio" name={`action-policy-${step.id}`} checked={config.failurePolicy===value} onChange={()=>setConfig(c=>({...c,failurePolicy:value}))} className="accent-orange-500"/><span>{label}</span>{value==='RETRY'&&config.failurePolicy==='RETRY'&&<><input type="number" min="1" max="10" value={config.retryCount} onChange={e=>setConfig(c=>({...c,retryCount:Number(e.target.value)}))} className="w-14 rounded border border-grayBorder px-2 py-1 text-center"/><span>lần</span></>}</label>)}</div></section>
   <section className="border-t border-grayBorder pt-5"><SectionLabel>Timeout</SectionLabel><div className="flex items-center justify-between text-xs text-slate-600"><span>Thời gian chờ tối đa trước khi coi là lỗi</span><label className="flex items-center gap-2"><input type="number" min="1" max="300" value={config.timeoutSeconds} onChange={e=>setConfig(c=>({...c,timeoutSeconds:Number(e.target.value)}))} className="w-16 rounded-md border border-grayBorder px-2 py-2 text-center"/> giây</label></div></section>
   {message&&<p className={`rounded-lg px-3 py-2 text-xs ${message.startsWith('Đã')?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-600'}`}>{message}</p>}
  </div>
 </PanelFrame>;
}

function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-[11px] font-medium text-slate-600">{label}</span>{children}</label>}
async function load(url){const response=await apiFetch(url);if(!response.ok)throw new Error(await error(response));return response.json()}
async function error(response){const body=await response.json().catch(()=>null);return body?.message||'Không thể lưu cấu hình'}
