import { useEffect, useState } from 'react';
import { Bell, Database, Globe2, Plus, Settings2, Trash2 } from 'lucide-react';
import { apiFetch } from '../../api';
import { PanelFrame, SectionLabel } from './StepPanelShared';
import CalculatedOutputEditor from '../CalculatedOutputEditor';

const DEFAULTS={actionType:'API_CALL',connectorId:'',pathTemplate:'',endpointUrl:'',httpMethod:'POST',payloadTemplate:'{\n  "requestCode": "{{requestCode}}"\n}',queryParams:[],headers:[],responseMappings:[],responseSelection:{mode:'ROOT',collectionJsonPath:'$',filterJsonPath:'$.id',expectedValueTemplate:''},notificationChannel:'IN_APP',notificationTitle:'Thông báo workflow',notificationBody:'Yêu cầu {{requestCode}} đã được xử lý.',webhookUrl:'',targetType:'REQUEST',recordType:'',newStatus:'COMPLETED',calculatedOutputs:[],mappings:[],failurePolicy:'STOP',retryCount:3,maxAttempts:3,timeoutSeconds:30};
const ACTIONS=[['API_CALL','Gọi API qua Connector',Globe2],['SEND_NOTIFICATION','Gửi thông báo',Bell],['UPDATE_DATA','Cập nhật dữ liệu workflow',Database],['CALCULATE_OUTPUT','Tính cột output',Database]];

export default function SystemActionStepPanel({workflowId,step,onClose,onDelete}){
 const [config,setConfig]=useState(DEFAULTS),[fields,setFields]=useState([]),[connectors,setConnectors]=useState([]),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{Promise.all([load(`/api/workflows/${workflowId}/steps/${step.id}/config`),load(`/api/workflows/${workflowId}/fields`),load('/api/connectors')]).then(([saved,items,connectorRows])=>{const rest=(connectorRows||[]).filter(item=>item.connectorType==='REST'&&item.active!==false);let normalized={...DEFAULTS,...saved,responseSelection:{...DEFAULTS.responseSelection,...saved?.responseSelection},mappings:Array.isArray(saved?.mappings)?saved.mappings:[],queryParams:Array.isArray(saved?.queryParams)?saved.queryParams:[],headers:Array.isArray(saved?.headers)?saved.headers:[],responseMappings:Array.isArray(saved?.responseMappings)?saved.responseMappings:[]};if(normalized.actionType==='API_CALL'&&!normalized.connectorId&&normalized.endpointUrl){const match=rest.find(item=>normalized.endpointUrl.startsWith(item.config?.baseUrl||'__none__'));if(match)normalized={...normalized,connectorId:match.id,pathTemplate:normalized.endpointUrl.slice((match.config?.baseUrl||'').length).replace(/^\//,'')}}setConfig(normalized);setFields(Array.isArray(items)?items:[]);setConnectors(rest)}).catch(e=>setMessage(e.message));},[workflowId,step.id]);
 const changeList=(key,index,name,value)=>setConfig(c=>({...c,[key]:c[key].map((item,i)=>i===index?{...item,[name]:value}:item)}));
 const remove=(key,index)=>setConfig(c=>({...c,[key]:c[key].filter((_,i)=>i!==index)}));
 const add=(key,value)=>setConfig(c=>({...c,[key]:[...(c[key]||[]),value]}));
 const save=async()=>{setSaving(true);setMessage('');try{const response=await apiFetch(`/api/workflows/${workflowId}/steps/${step.id}/config/system-action`,{method:'PUT',body:JSON.stringify(config)});if(!response.ok)throw new Error(await error(response));setConfig({...DEFAULTS,...await response.json()});setMessage('Đã lưu cấu hình System Action Step.')}catch(e){setMessage(e.message)}finally{setSaving(false)}};
 return <PanelFrame icon={Settings2} title="Cấu hình: System Action Step" subtitle="Tự động gọi hệ thống ngoài hoặc cập nhật dữ liệu workflow" onClose={onClose} onDelete={onDelete} footer={<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-grayBorder px-4 py-2.5 text-sm text-slate-600">Hủy</button><button type="button" onClick={save} disabled={saving} className="btn-primary min-w-[150px] py-2.5 text-sm disabled:opacity-60">{saving?'Đang lưu...':'Lưu cấu hình'}</button></div>}>
  <div className="space-y-6">
   <section><SectionLabel>Loại hành động</SectionLabel><div className="grid grid-cols-2 gap-2">{ACTIONS.map(([value,label,Icon])=><button key={value} type="button" onClick={()=>setConfig(c=>({...c,actionType:value}))} className={`flex min-h-[72px] flex-col items-center justify-center gap-2 rounded-lg border px-2 py-3 text-[11px] font-semibold ${config.actionType===value?'border-orange-500 bg-orange-50 text-orange-600':'border-grayBorder bg-white text-slate-600 hover:border-orange-200'}`}><Icon size={18}/><span className="text-center">{label}</span></button>)}</div>{['CREATE_RECORD','UPDATE_STATUS'].includes(config.actionType)&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-700">Đây là cấu hình cũ. Hãy chọn “Gọi API qua Connector” để cập nhật hệ thống ngoài, hoặc “Cập nhật dữ liệu workflow” cho dữ liệu nội bộ.</p>}</section>
   {config.actionType==='CALCULATE_OUTPUT'&&<><CalculatedOutputEditor value={config.calculatedOutputs||[]} onChange={calculatedOutputs=>setConfig(c=>({...c,calculatedOutputs}))} fields={fields}/><p className="text-xs text-slate-500">Kết quả được lưu vào snapshot và chuyển sang bước tiếp theo.</p></>}
   {config.actionType==='API_CALL'&&<ConnectorRequest config={config} setConfig={setConfig} connectors={connectors} fields={fields} add={add} changeList={changeList} remove={remove}/>}
   {config.actionType==='SEND_NOTIFICATION'&&<section className="space-y-4"><SectionLabel>Thông báo</SectionLabel><Field label="Kênh"><select value={config.notificationChannel} onChange={e=>setConfig(c=>({...c,notificationChannel:e.target.value}))} className="input-field bg-white"><option value="IN_APP">In-app</option><option value="EMAIL">Email</option><option value="TEAMS">Teams</option><option value="WEBHOOK">Webhook</option></select></Field>{config.notificationChannel==='WEBHOOK'&&<Field label="Webhook URL"><input value={config.webhookUrl||''} onChange={e=>setConfig(c=>({...c,webhookUrl:e.target.value}))} className="input-field"/></Field>}<Field label="Tiêu đề"><input value={config.notificationTitle} onChange={e=>setConfig(c=>({...c,notificationTitle:e.target.value}))} className="input-field"/></Field><Field label="Nội dung"><textarea rows={5} value={config.notificationBody} onChange={e=>setConfig(c=>({...c,notificationBody:e.target.value}))} className="input-field resize-y"/></Field></section>}
   {config.actionType==='UPDATE_DATA'&&<MappingEditor title="Cập nhật field trong workflow" mappings={config.mappings} fields={fields} add={()=>add('mappings',{sourceFieldKey:fields[0]?.fieldKey||'',targetField:fields[0]?.fieldKey||'',valueTemplate:''})} update={(i,k,v)=>changeList('mappings',i,k,v)} remove={i=>remove('mappings',i)}/>}
   <section className="border-t border-grayBorder pt-5"><SectionLabel>Thực thi</SectionLabel><div className="grid grid-cols-2 gap-3"><Field label="Timeout mỗi lần (giây)"><input type="number" min="1" max="300" value={config.timeoutSeconds} onChange={e=>setConfig(c=>({...c,timeoutSeconds:Number(e.target.value)}))} className="input-field"/></Field>{config.actionType==='API_CALL'&&<Field label="Số lần thử tối đa"><input type="number" min="1" max="10" value={config.maxAttempts} onChange={e=>setConfig(c=>({...c,maxAttempts:Number(e.target.value)}))} className="input-field"/></Field>}</div>{config.actionType==='API_CALL'&&<p className="mt-2 text-xs text-slate-500">Hết số lần thử, workflow chuyển sang nhánh SYSTEM_FAIL.</p>}</section>
   {message&&<p className={`rounded-lg px-3 py-2 text-xs ${message.startsWith('Đã')?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-600'}`}>{message}</p>}
  </div>
 </PanelFrame>;
}

function ConnectorRequest({config,setConfig,connectors,fields,add,changeList,remove}) {
 const bodyEnabled=['POST','PUT','PATCH'].includes(config.httpMethod);
 const selection=config.responseSelection||DEFAULTS.responseSelection;
 const setSelection=(name,value)=>setConfig(c=>({...c,responseSelection:{...DEFAULTS.responseSelection,...c.responseSelection,[name]:value}}));
 const filters=String(selection.mode||'ROOT').startsWith('FILTER_');
 return <div className="space-y-6">
  <div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-xs leading-5 text-blue-700">
   API trả về được lưu trong lịch sử execution để tra cứu. Chỉ các giá trị bạn mapping bên dưới mới được ghi vào dữ liệu workflow (snapshot), vì vậy bước sau có thể dùng <code>{'{{fieldKey}}'}</code> hoặc chọn field đó trong điều kiện rẽ nhánh.
  </div>
  <section className="space-y-4"><SectionLabel>1. Gửi request qua Connector</SectionLabel><Field label="REST Connector *"><select required value={config.connectorId||''} onChange={e=>setConfig(c=>({...c,connectorId:e.target.value,endpointUrl:''}))} className="input-field bg-white"><option value="">Chọn connector...</option>{connectors.map(item=><option key={item.id} value={item.id}>{item.name} · {item.config?.baseUrl}</option>)}</select></Field><div className="grid grid-cols-[110px_1fr] gap-3"><Field label="Method"><select value={config.httpMethod} onChange={e=>setConfig(c=>({...c,httpMethod:e.target.value}))} className="input-field bg-white"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></Field><Field label="Path tương đối"><input value={config.pathTemplate||''} onChange={e=>setConfig(c=>({...c,pathTemplate:e.target.value}))} className="input-field" placeholder="orders/{{orderId}}"/></Field></div>{bodyEnabled&&<Field label="Request body (JSON)"><textarea rows={7} value={config.payloadTemplate} onChange={e=>setConfig(c=>({...c,payloadTemplate:e.target.value}))} className="input-field resize-y font-mono text-xs"/></Field>}</section>
  <NameValueEditor title="Query parameters" rows={config.queryParams} onAdd={()=>add('queryParams',{name:'',valueTemplate:''})} onChange={(i,k,v)=>changeList('queryParams',i,k,v)} onRemove={i=>remove('queryParams',i)}/>
  <NameValueEditor title="Custom headers" rows={config.headers} onAdd={()=>add('headers',{name:'',valueTemplate:''})} onChange={(i,k,v)=>changeList('headers',i,k,v)} onRemove={i=>remove('headers',i)}/>
  <section className="space-y-3"><SectionLabel>2. Chọn phần dữ liệu trong response</SectionLabel>
   <Field label="Cách chọn kết quả"><select value={selection.mode||'ROOT'} onChange={e=>setSelection('mode',e.target.value)} className="input-field bg-white"><option value="ROOT">Dùng toàn bộ response</option><option value="FIRST">Lấy phần tử đầu tiên</option><option value="LAST">Lấy phần tử cuối cùng</option><option value="FILTER_FIRST">Lọc rồi lấy phần tử đầu tiên</option><option value="FILTER_LAST">Lọc rồi lấy phần tử cuối cùng</option></select></Field>
   {selection.mode!=='ROOT'&&<Field label="JSONPath tới mảng kết quả"><input value={selection.collectionJsonPath||''} onChange={e=>setSelection('collectionJsonPath',e.target.value)} className="input-field font-mono text-xs" placeholder="$.data.items"/></Field>}
   {filters&&<div className="grid grid-cols-2 gap-3"><Field label="JSONPath trong mỗi phần tử"><input value={selection.filterJsonPath||''} onChange={e=>setSelection('filterJsonPath',e.target.value)} className="input-field font-mono text-xs" placeholder="$.status"/></Field><Field label="Giá trị cần khớp"><input value={selection.expectedValueTemplate||''} onChange={e=>setSelection('expectedValueTemplate',e.target.value)} className="input-field text-xs" placeholder="ACTIVE hoặc {{status}}"/></Field></div>}
   <p className="text-xs text-slate-500">Ví dụ: chọn <code>$.data.items</code>, lọc <code>$.status = ACTIVE</code>, rồi lấy bản ghi cuối cùng.</p>
  </section>
  <section><SectionLabel>3. Lưu kết quả vào field workflow</SectionLabel><p className="mb-3 text-xs leading-5 text-slate-500">JSONPath được tính từ kết quả đã chọn ở mục 2. Mỗi giá trị sẽ ghi vào Field workflow đích và được chuyển tiếp tự động.</p>
   <div className="mb-1 grid grid-cols-[1fr_1fr_auto_auto] gap-2 px-1 text-[10px] font-semibold uppercase text-slate-400"><span>JSONPath nguồn</span><span>Field workflow đích</span><span>Bắt buộc</span><span/></div>
   <div className="space-y-2">{config.responseMappings.map((row,index)=><div key={index} className="grid grid-cols-[1fr_1fr_auto_auto] items-center gap-2"><input value={row.jsonPath||''} onChange={e=>changeList('responseMappings',index,'jsonPath',e.target.value)} className="input-field font-mono text-xs" placeholder="$.id"/><select value={row.targetField||''} onChange={e=>changeList('responseMappings',index,'targetField',e.target.value)} className="input-field bg-white"><option value="">Field đích...</option>{fields.map(field=><option key={field.fieldKey} value={field.fieldKey}>{field.label} ({field.fieldKey})</option>)}</select><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={!!row.required} onChange={e=>changeList('responseMappings',index,'required',e.target.checked)}/>Có</label><IconButton onClick={()=>remove('responseMappings',index)}/></div>)}</div><AddButton onClick={()=>add('responseMappings',{jsonPath:'$.id',targetField:'',required:false,defaultValue:null})}>Thêm response mapping</AddButton>
  </section>
 </div>
}
function NameValueEditor({title,rows,onAdd,onChange,onRemove}){return <section><SectionLabel>{title}</SectionLabel><div className="space-y-2">{rows.map((row,index)=><div key={index} className="grid grid-cols-[1fr_1fr_36px] gap-2"><input value={row.name||''} onChange={e=>onChange(index,'name',e.target.value)} className="input-field text-xs" placeholder="Tên"/><input value={row.valueTemplate||''} onChange={e=>onChange(index,'valueTemplate',e.target.value)} className="input-field text-xs" placeholder="Giá trị hoặc {{fieldKey}}"/><IconButton onClick={()=>onRemove(index)}/></div>)}</div><AddButton onClick={onAdd}>Thêm</AddButton></section>}
function MappingEditor({title,mappings,fields,add,update,remove}){return <section><SectionLabel>{title}</SectionLabel><p className="mb-3 text-xs leading-5 text-slate-500">Sao chép Field nguồn hoặc giá trị tùy chỉnh vào Field đích trong snapshot. Bước kế tiếp thấy giá trị mới ngay lập tức và có thể dùng <code>{'{{fieldKey}}'}</code>.</p><div className="mb-1 grid grid-cols-[1fr_1fr_36px] gap-2 px-1 text-[10px] font-semibold uppercase text-slate-400"><span>Field nguồn</span><span>Field đích</span><span/></div><div className="space-y-2">{mappings.map((row,index)=><div key={index} className="grid grid-cols-[1fr_1fr_36px] gap-2"><select value={row.sourceFieldKey||''} onChange={e=>update(index,'sourceFieldKey',e.target.value)} className="input-field bg-white text-xs"><option value="">Giá trị tùy chỉnh</option>{fields.map(field=><option key={field.fieldKey} value={field.fieldKey}>{field.label} ({field.fieldKey})</option>)}</select><select value={row.targetField||''} onChange={e=>update(index,'targetField',e.target.value)} className="input-field bg-white text-xs"><option value="">Field đích...</option>{fields.map(field=><option key={field.fieldKey} value={field.fieldKey}>{field.label} ({field.fieldKey})</option>)}</select><IconButton onClick={()=>remove(index)}/>{!row.sourceFieldKey&&<input value={row.valueTemplate||''} onChange={e=>update(index,'valueTemplate',e.target.value)} className="input-field col-span-2 text-xs" placeholder="Nhập giá trị hoặc template {{fieldKey}}"/>}</div>)}</div><AddButton onClick={add}>Thêm mapping</AddButton></section>}
function AddButton({onClick,children}){return <button type="button" onClick={onClick} className="mt-2 flex w-full items-center justify-center gap-1 rounded-lg border border-dashed border-grayBorder py-2.5 text-xs font-medium text-slate-500 hover:border-orange-300 hover:text-orange-500"><Plus size={14}/>{children}</button>}
function IconButton({onClick}){return <button type="button" onClick={onClick} className="flex items-center justify-center text-gray-400 hover:text-red-500"><Trash2 size={15}/></button>}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-[11px] font-medium text-slate-600">{label}</span>{children}</label>}
async function load(url){const response=await apiFetch(url);if(!response.ok)throw new Error(await error(response));return response.json()}
async function error(response){const body=await response.json().catch(()=>null);return body?.message||'Không thể lưu cấu hình'}
