import { useEffect, useState } from 'react';
import { FileText, Plus, Pencil, Send, X, Trash2 } from 'lucide-react';
import { apiError, apiFetch } from '../api';
import AddFieldModal from '../components/panels/AddFieldModal';

const EMPTY={name:'',description:'',instruction:'',submissionMode:'SINGLE',recordRecipientFieldKey:'',maxBatchRows:500,fields:[]};

export default function FormsPage(){
 const [forms,setForms]=useState([]),[selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(null);
 const load=async()=>{const r=await apiFetch('/api/forms',{toast:false});if(!r.ok)throw new Error(await apiError(r));setForms(await r.json())};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const open=async form=>{setError('');const detail=await (await apiFetch(`/api/forms/${form.id}`)).json();let version=detail.draftVersion;if(!version){const r=await apiFetch(`/api/forms/${form.id}/versions`,{method:'POST'});if(!r.ok)return setError(await apiError(r));version=await r.json()}const r=await apiFetch(`/api/forms/versions/${version.id}`);const data=await r.json();setSelected(form.id);setDraft({...EMPTY,...data,name:data.formName||detail.name})};
 const create=async()=>{setBusy(true);const r=await apiFetch('/api/forms',{method:'POST',body:JSON.stringify({name:'Form mới',fields:[]})});setBusy(false);if(!r.ok)return setError(await apiError(r));await load();const data=await r.json();setSelected(data.formId);setDraft({...EMPTY,...data,name:data.formName})};
 const save=async()=>{setBusy(true);setError('');const r=await apiFetch(`/api/forms/${draft.formId}/versions/${draft.id}`,{method:'PUT',body:JSON.stringify(draft)});setBusy(false);if(!r.ok)return setError(await apiError(r));setDraft({...draft,...await r.json()});await load()};
 const publish=async()=>{await save();setBusy(true);const r=await apiFetch(`/api/forms/${draft.formId}/versions/${draft.id}/publish`,{method:'POST'});setBusy(false);if(!r.ok)return setError(await apiError(r));setDraft({...draft,...await r.json()});await load()};
 const saveField=async field=>{setDraft(v=>({...v,fields:modal?.index>=0?v.fields.map((x,i)=>i===modal.index?field:x):[...v.fields,field]}));setModal(null);return true};
 return <div className="space-y-6 p-6"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-800">Form Management</h1><p className="text-sm text-slate-500">Thiết kế form dùng chung rồi gắn phiên bản đã publish vào workflow.</p></div><button disabled={busy} onClick={create} className="btn-primary flex items-center gap-2"><Plus size={17}/>Tạo Form</button></header>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}
 <div className="grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="space-y-2">{forms.map(form=><button key={form.id} onClick={()=>open(form)} className={`w-full rounded-xl border bg-white p-4 text-left ${selected===form.id?'border-orange-400':'border-slate-200'}`}><div className="flex gap-3"><FileText className="text-orange-500" size={20}/><div><p className="font-bold text-slate-800">{form.name}</p><p className="mt-1 text-xs text-slate-500">Published v{form.latestPublishedVersion?.versionNumber||'—'}{form.draftVersion?` · Draft v${form.draftVersion.versionNumber}`:''}</p></div></div></button>)}</aside>
 {draft?<main className="rounded-xl border bg-white p-6"><div className="flex items-start justify-between gap-4"><div className="grid flex-1 gap-3 md:grid-cols-2"><input value={draft.name} disabled={draft.status!=='DRAFT'} onChange={e=>setDraft({...draft,name:e.target.value})} className="input-field text-lg font-bold"/><input value={draft.description||''} disabled={draft.status!=='DRAFT'} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Mô tả form" className="input-field"/></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">v{draft.versionNumber} · {draft.status}</span></div>
 <textarea value={draft.instruction||''} disabled={draft.status!=='DRAFT'} onChange={e=>setDraft({...draft,instruction:e.target.value})} placeholder="Hướng dẫn người gửi" className="input-field mt-4 min-h-20"/>
 <div className="mt-5 grid gap-3 md:grid-cols-3"><select value={draft.submissionMode} disabled={draft.status!=='DRAFT'} onChange={e=>setDraft({...draft,submissionMode:e.target.value})} className="input-field bg-white"><option value="SINGLE">Form đơn</option><option value="BATCH">Danh sách CSV</option></select>{draft.submissionMode==='BATCH'&&<><input type="number" min="1" max="2000" value={draft.maxBatchRows} onChange={e=>setDraft({...draft,maxBatchRows:Number(e.target.value)})} className="input-field"/><select value={draft.recordRecipientFieldKey||''} onChange={e=>setDraft({...draft,recordRecipientFieldKey:e.target.value})} className="input-field bg-white"><option value="">Không có cột người nhận</option>{draft.fields.filter(f=>f.type==='TEXT').map(f=><option key={f.fieldKey} value={f.fieldKey}>{f.label}</option>)}</select></>}</div>
 <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-slate-700">Các field</h2>{draft.status==='DRAFT'&&<button onClick={()=>setModal({index:-1})} className="text-sm font-semibold text-orange-600">+ Thêm field</button>}</div><div className="space-y-2">{draft.fields.map((field,index)=><div key={`${field.fieldKey}-${index}`} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-semibold text-slate-700">{field.label}</p><p className="text-xs text-slate-400">{field.fieldKey} · {field.type}{field.required?' · Bắt buộc':''}</p></div>{draft.status==='DRAFT'&&<div className="flex gap-2"><button onClick={()=>setModal({index,field})}><Pencil size={15}/></button><button onClick={()=>setDraft(v=>({...v,fields:v.fields.filter((_,i)=>i!==index)}))} className="text-red-500"><Trash2 size={15}/></button></div>}</div>)}</div></section>
 {draft.status==='DRAFT'&&<div className="mt-6 flex justify-end gap-3"><button disabled={busy} onClick={save} className="rounded-lg border px-4 py-2 text-sm font-semibold">Lưu draft</button><button disabled={busy} onClick={publish} className="btn-primary flex items-center gap-2"><Send size={15}/>Publish Form</button></div>}</main>:<main className="rounded-xl border border-dashed p-12 text-center text-sm text-slate-400">Chọn hoặc tạo một form để thiết kế.</main>}</div>
 <AddFieldModal isOpen={!!modal} editingField={modal?.field} onClose={()=>setModal(null)} onSave={saveField}/></div>
}
