import { useEffect, useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import { apiFetch } from '../api';
import InstanceStatusBadge from '../components/InstanceStatusBadge';
import Pagination from '../components/Pagination';
import InstanceJourney from '../components/InstanceJourney';
import { useParams } from 'react-router-dom';

export default function InstancesPage(){
 const {instanceId}=useParams();
 const [instances,setInstances]=useState([]),[selectedId,setSelectedId]=useState(''),[history,setHistory]=useState([]),[batchData,setBatchData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[workflow,setWorkflow]=useState(''),[page,setPage]=useState(0);
 const pageSize=8;
 useEffect(()=>{(async()=>{setLoading(true);const response=await apiFetch('/api/instances');if(response.ok){const items=await response.json();setInstances(items);setSelectedId(instanceId&&items.some(item=>item.id===instanceId)?instanceId:(items[0]?.id||''))}else setError(await apiError(response));setLoading(false)})()},[instanceId]);
 useEffect(()=>{if(!selectedId){setHistory([]);return}(async()=>{const response=await apiFetch(`/api/instances/${selectedId}/history`);if(response.ok)setHistory(await response.json())})()},[selectedId]);
 const workflows=useMemo(()=>[...new Set(instances.map(item=>item.workflowName))].sort((a,b)=>a.localeCompare(b,'vi')),[instances]);
 const filtered=useMemo(()=>instances.filter(item=>`${item.requestCode} ${item.batchId||''} ${item.workflowName} ${item.currentStepLabel} ${item.createdByName}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))&&(!status||item.status===status)&&(!workflow||item.workflowName===workflow)),[instances,query,status,workflow]);
 const displayed=filtered.slice(page*pageSize,(page+1)*pageSize),selected=instances.find(item=>item.id===selectedId);
 useEffect(()=>{if(!selected?.batch){setBatchData(null);return}(async()=>{const response=await apiFetch(`/api/instances/${selected.id}/batch-records?page=0&size=100`);if(response.ok)setBatchData(await response.json())})()},[selected?.id,selected?.batch]);
 useEffect(()=>setPage(0),[query,status,workflow]);
 return <div className="flex h-full min-h-[580px] flex-col overflow-hidden rounded-xl border border-grayBorder bg-white shadow-sm">
  <header className="border-b border-grayBorder px-6 py-4"><h1 className="text-xl font-bold text-slate-800">Workflow Instances</h1><p className="mt-1 text-sm text-gray-400">Theo dõi và quản lý trạng thái các luồng quy trình đang chạy</p></header>
  {error&&<div className="mx-6 mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}
  <div className="flex min-h-0 flex-1">
   <section className="flex min-w-0 flex-1 flex-col border-r border-grayBorder"><div className="flex flex-wrap items-center gap-3 px-6 py-4"><div className="relative min-w-[230px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-lg border border-grayBorder py-2 pl-9 pr-3 text-sm outline-none focus:border-orange-400" placeholder="Tìm mã yêu cầu, workflow..."/></div><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-lg border border-grayBorder bg-white px-3 py-2 text-sm"><option value="">Trạng thái: Tất cả</option><option value="RUNNING">Đang xử lý</option><option value="COMPLETED">Hoàn thành</option><option value="APPROVED">Đã duyệt</option><option value="REJECTED">Từ chối</option><option value="CANCELLED">Hủy bỏ</option><option value="WITHDRAWN">Đã thu hồi</option></select><select value={workflow} onChange={event=>setWorkflow(event.target.value)} className="max-w-[210px] rounded-lg border border-grayBorder bg-white px-3 py-2 text-sm"><option value="">Quy trình: Tất cả</option>{workflows.map(item=><option key={item}>{item}</option>)}</select></div>
    <div className="min-h-0 flex-1 overflow-auto px-6"><table className="w-full text-left"><thead className="sticky top-0 z-10 bg-white text-[11px] font-bold uppercase text-gray-500"><tr className="border-b border-grayBorder"><th className="px-3 py-3">Mã yêu cầu</th><th className="px-3 py-3">Workflow / bước hiện tại</th><th className="px-3 py-3">Trạng thái</th><th className="px-3 py-3">Thời gian bắt đầu</th></tr></thead><tbody>{loading?<tr><td colSpan="4" className="py-12 text-center text-sm text-gray-400">Đang tải instances...</td></tr>:displayed.map(item=><tr key={item.id} onClick={()=>setSelectedId(item.id)} className={`cursor-pointer border-b border-slate-100 text-sm hover:bg-orange-50/40 ${selectedId===item.id?'border-l-2 border-l-orange-500 bg-orange-50/50':''}`}><td className="px-3 py-4 font-bold text-slate-800">{item.requestCode}</td><td className="px-3 py-4"><p className="font-semibold text-slate-800">{item.workflowName}</p><p className="mt-1 text-xs text-gray-500">{item.currentStepLabel||'Đã kết thúc'} · Tạo bởi {item.createdByName}</p></td><td className="px-3 py-4"><InstanceStatusBadge value={item.status}/></td><td className="px-3 py-4 text-xs text-gray-500">{formatDate(item.startedAt)}</td></tr>)}</tbody></table></div>
    <Pagination page={page} totalItems={filtered.length} pageSize={pageSize} onPageChange={setPage} itemLabel="instances" />
   </section>
   <aside className="w-[420px] shrink-0 overflow-auto bg-white p-6"><h2 className="mb-1 text-base font-bold text-slate-800">Tiến trình: {selected?.requestCode||'—'}</h2>{selected&&<><p className="mb-6 text-xs text-gray-400">{selected.workflowName} · v{selected.workflowVersion}</p>{selected.batch?<BatchSummary instance={selected} data={batchData}/>:<InstanceJourney history={history} instance={selected}/>} {selected.conditionBlocked&&selected.status==='RUNNING'&&<p className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700">Điều kiện chuyển bước hiện chưa thỏa.</p>}{!selected.batch&&<div className="mt-7 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase text-gray-400">Dữ liệu request</p><div className="mt-3 space-y-2">{Object.entries(selected.fields||{}).slice(0,6).map(([key,value])=><div key={key} className="flex justify-between gap-3 text-xs"><span className="text-gray-500">{key}</span><span className="max-w-[180px] truncate font-medium text-slate-700">{summarizeValue(value)}</span></div>)}</div></div>}</>}</aside>
  </div>
 </div>;
}
function BatchSummary({instance,data}){const records=data?.items||[];return <div className="space-y-4"><div className="rounded-xl border border-violet-200 bg-violet-50 p-4"><p className="text-xs font-bold uppercase text-violet-600">Batch instance · {instance.batchTotal} hồ sơ</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(instance.batchStatusCounts||{}).map(([key,value])=><span key={key} className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-slate-600">{key}: {value}</span>)}</div></div><div className="max-h-[430px] overflow-auto rounded-xl border border-slate-200"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="px-3 py-2">Dòng</th><th className="px-3 py-2">Bước hiện tại</th><th className="px-3 py-2">Trạng thái</th></tr></thead><tbody>{records.map(record=><tr key={record.rowNumber} className="border-t border-slate-100"><td className="px-3 py-2 font-bold text-violet-600">{record.rowNumber}</td><td className="px-3 py-2 text-slate-600">{record.currentStepLabel}</td><td className="px-3 py-2 text-slate-600">{record.status}</td></tr>)}</tbody></table></div>{data&&data.total>records.length&&<p className="text-[10px] text-slate-400">Đang hiển thị {records.length}/{data.total} dòng đầu tiên.</p>}</div>}
function formatDate(value){return value?new Date(value).toLocaleString('vi-VN'):'—'}
function summarizeValue(value){if(value&&typeof value==='object'&&value.name)return `📎 ${value.name}`;if(value&&typeof value==='object')return JSON.stringify(value);return String(value??'—')}
async function apiError(response){const body=await response.json().catch(()=>null);return body?.message||`HTTP ${response.status}`}
