import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Eye, Search, X } from 'lucide-react';
import { apiFetch } from '../api';
import InstanceStatusBadge from '../components/InstanceStatusBadge';
import Pagination from '../components/Pagination';
import InstanceJourney from '../components/InstanceJourney';
import { useParams } from 'react-router-dom';

export default function InstancesPage(){
 const {instanceId}=useParams();
 const [instances,setInstances]=useState([]),[selectedId,setSelectedId]=useState(''),[history,setHistory]=useState([]),[systemActions,setSystemActions]=useState([]),[batchData,setBatchData]=useState(null),[batchPage,setBatchPage]=useState(0),[rowDetail,setRowDetail]=useState(null),[rowLoading,setRowLoading]=useState(false),[historyError,setHistoryError]=useState(''),[batchError,setBatchError]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[workflow,setWorkflow]=useState(''),[page,setPage]=useState(0);
 const pageSize=8;
 useEffect(()=>{(async()=>{setLoading(true);const response=await apiFetch('/api/instances');if(response.ok){const items=await response.json();setInstances(items);setSelectedId(instanceId&&items.some(item=>item.id===instanceId)?instanceId:(items[0]?.id||''))}else setError(await apiError(response));setLoading(false)})()},[instanceId]);
 useEffect(()=>{if(!selectedId){setHistory([]);setSystemActions([]);return}(async()=>{setHistoryError('');const [historyResponse,actionsResponse]=await Promise.all([apiFetch(`/api/instances/${selectedId}/history`),apiFetch(`/api/instances/${selectedId}/system-actions`)]);if(historyResponse.ok)setHistory(await historyResponse.json());else{setHistory([]);setHistoryError(await apiError(historyResponse,'Không thể tải lịch sử xử lý.'))}if(actionsResponse.ok)setSystemActions(await actionsResponse.json());else setSystemActions([])})()},[selectedId]);
 const workflows=useMemo(()=>[...new Set(instances.map(item=>item.workflowName))].sort((a,b)=>a.localeCompare(b,'vi')),[instances]);
 const filtered=useMemo(()=>instances.filter(item=>`${item.requestCode} ${item.batchId||''} ${item.workflowName} ${item.currentStepLabel} ${item.createdByName}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))&&(!status||item.status===status)&&(!workflow||item.workflowName===workflow)),[instances,query,status,workflow]);
 const displayed=filtered.slice(page*pageSize,(page+1)*pageSize),selected=instances.find(item=>item.id===selectedId);
 useEffect(()=>{setBatchPage(0);setRowDetail(null)},[selected?.id]);
 useEffect(()=>{if(!selected?.batch){setBatchData(null);return}(async()=>{setBatchError('');const response=await apiFetch(`/api/instances/${selected.id}/batch-records?page=${batchPage}&size=20`);if(response.ok)setBatchData(await response.json());else{setBatchData(null);setBatchError(await apiError(response,'Không thể tải danh sách hồ sơ.'))}})()},[selected?.id,selected?.batch,batchPage]);
 const openBatchRow=async rowNumber=>{setRowLoading(true);setBatchError('');const response=await apiFetch(`/api/instances/${selected.id}/batch-records/${rowNumber}`);if(response.ok)setRowDetail(await response.json());else setBatchError(await apiError(response,'Không thể tải chi tiết dòng.'));setRowLoading(false)};
 useEffect(()=>setPage(0),[query,status,workflow]);
 return <div className="flex h-full min-h-[580px] flex-col overflow-hidden rounded-xl border border-grayBorder bg-white shadow-sm">
  <header className="border-b border-grayBorder px-6 py-4"><h1 className="text-xl font-bold text-slate-800">Workflow Instances</h1><p className="mt-1 text-sm text-gray-400">Theo dõi và quản lý trạng thái các luồng quy trình đang chạy</p></header>
  {error&&<div className="mx-6 mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}
  <div className="flex min-h-0 flex-1">
   <section className="flex min-w-0 flex-1 flex-col border-r border-grayBorder"><div className="flex flex-wrap items-center gap-3 px-6 py-4"><div className="relative min-w-[230px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-lg border border-grayBorder py-2 pl-9 pr-3 text-sm outline-none focus:border-orange-400" placeholder="Tìm mã yêu cầu, workflow..."/></div><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-lg border border-grayBorder bg-white px-3 py-2 text-sm"><option value="">Trạng thái: Tất cả</option><option value="RUNNING">Đang xử lý</option><option value="COMPLETED">Hoàn thành</option><option value="APPROVED">Đã duyệt</option><option value="REJECTED">Từ chối</option><option value="CANCELLED">Hủy bỏ</option><option value="WITHDRAWN">Đã thu hồi</option></select><select value={workflow} onChange={event=>setWorkflow(event.target.value)} className="max-w-[210px] rounded-lg border border-grayBorder bg-white px-3 py-2 text-sm"><option value="">Quy trình: Tất cả</option>{workflows.map(item=><option key={item}>{item}</option>)}</select></div>
    <div className="min-h-0 flex-1 overflow-auto px-6"><table className="w-full text-left"><thead className="sticky top-0 z-10 bg-white text-[11px] font-bold uppercase text-gray-500"><tr className="border-b border-grayBorder"><th className="px-3 py-3">Mã yêu cầu</th><th className="px-3 py-3">Workflow / bước hiện tại</th><th className="px-3 py-3">Trạng thái</th><th className="px-3 py-3">Thời gian bắt đầu</th></tr></thead><tbody>{loading?<tr><td colSpan="4" className="py-12 text-center text-sm text-gray-400">Đang tải instances...</td></tr>:displayed.map(item=><tr key={item.id} onClick={()=>setSelectedId(item.id)} className={`cursor-pointer border-b border-slate-100 text-sm hover:bg-orange-50/40 ${selectedId===item.id?'border-l-2 border-l-orange-500 bg-orange-50/50':''}`}><td className="px-3 py-4 font-bold text-slate-800">{item.requestCode}</td><td className="px-3 py-4"><p className="font-semibold text-slate-800">{item.workflowName}</p><p className="mt-1 text-xs text-gray-500">{item.currentStepLabel||'Đã kết thúc'} · Tạo bởi {item.createdByName}</p></td><td className="px-3 py-4"><InstanceStatusBadge value={item.status}/></td><td className="px-3 py-4 text-xs text-gray-500">{formatDate(item.startedAt)}</td></tr>)}</tbody></table></div>
    <Pagination page={page} totalItems={filtered.length} pageSize={pageSize} onPageChange={setPage} itemLabel="instances" />
   </section>
   <aside className="w-[520px] shrink-0 overflow-auto bg-white p-6"><h2 className="mb-1 text-base font-bold text-slate-800">Tiến trình: {selected?.requestCode||'—'}</h2>{selected&&<><p className="mb-6 text-xs text-gray-400">{selected.workflowName} · v{selected.workflowVersion}</p>{historyError?<p className="mb-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-600">{historyError}</p>:<InstanceJourney history={history} instance={selected}/>} {selected.batch&&<BatchSummary instance={selected} data={batchData} error={batchError} loading={rowLoading} onOpen={openBatchRow} onPage={setBatchPage}/>}<SystemActionExecutions rows={systemActions}/>{selected.conditionBlocked&&selected.status==='RUNNING'&&<p className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700">Điều kiện chuyển bước hiện chưa thỏa.</p>}{!selected.batch&&<div className="mt-7 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase text-gray-400">Dữ liệu request</p><div className="mt-3 space-y-2">{Object.entries(selected.fields||{}).slice(0,6).map(([key,value])=><div key={key} className="flex justify-between gap-3 text-xs"><span className="text-gray-500">{key}</span><span className="max-w-[180px] truncate font-medium text-slate-700">{summarizeValue(value)}</span></div>)}</div></div>}</>}</aside>
  </div>
  {rowDetail&&<BatchRecordDrawer detail={rowDetail} records={batchData?.items||[]} loading={rowLoading} onOpen={openBatchRow} onClose={()=>setRowDetail(null)}/>}
 </div>;
}
function BatchSummary({instance,data,error,loading,onOpen,onPage}){const records=data?.items||[];return <section className="mt-7 space-y-4"><div className="rounded-xl border border-violet-200 bg-violet-50 p-4"><p className="text-xs font-bold uppercase text-violet-600">Batch instance · {instance.batchTotal} hồ sơ</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(instance.batchStatusCounts||{}).map(([key,value])=><span key={key} className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-slate-600">{key}: {value}</span>)}</div></div>{error&&<p className="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-600">{error}</p>}<div className="max-h-[430px] overflow-auto rounded-xl border border-slate-200"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="px-3 py-2">Dòng</th><th className="px-3 py-2">Trạng thái</th><th className="px-3 py-2 text-right">Chi tiết</th></tr></thead><tbody>{records.map(record=><tr key={`${record.rowNumber}-${record.revision}`} className="border-t border-slate-100 hover:bg-violet-50"><td className="px-3 py-2 font-bold text-violet-600">{record.rowNumber}</td><td className="px-3 py-2 text-slate-600">{record.status}</td><td className="px-3 py-2 text-right"><button type="button" onClick={()=>onOpen(record.rowNumber)} className="inline-flex items-center gap-1 rounded-lg border border-violet-200 bg-white px-2.5 py-1.5 font-semibold text-violet-600 hover:bg-violet-50"><Eye size={13}/>Xem chi tiết</button></td></tr>)}</tbody></table>{!records.length&&!error&&<p className="p-5 text-center text-xs text-slate-400">Không có dòng nào bạn được phép xem.</p>}</div>{data&&<div className="flex items-center justify-between text-xs text-slate-500"><span>{data.total} dòng · trang {(data.page||0)+1}/{Math.max(data.totalPages||1,1)}</span><div className="flex gap-2"><button disabled={loading||data.page<=0} onClick={()=>onPage(data.page-1)} className="rounded border p-1.5 disabled:opacity-30"><ChevronLeft size={14}/></button><button disabled={loading||data.page+1>=data.totalPages} onClick={()=>onPage(data.page+1)} className="rounded border p-1.5 disabled:opacity-30"><ChevronRight size={14}/></button></div></div>}</section>}

function BatchRecordDrawer({detail,records,loading,onOpen,onClose}){const index=records.findIndex(row=>row.rowNumber===detail.rowNumber),previous=records[index-1],next=records[index+1];return <div className="fixed inset-0 z-[160] bg-slate-900/35" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="ml-auto flex h-full w-full max-w-xl flex-col bg-white shadow-2xl"><header className="flex items-start justify-between border-b px-6 py-5"><div><h2 className="text-lg font-bold text-slate-800">Chi tiết dòng {detail.rowNumber}</h2><p className="mt-1 text-xs text-slate-500">{detail.businessKey||'Không có khóa nghiệp vụ'} · revision {detail.revision||1}</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18}/></button></header><div className="flex-1 space-y-6 overflow-auto p-6"><section className="grid grid-cols-2 gap-3 rounded-xl border bg-slate-50 p-4 text-xs"><Info label="Trạng thái" value={detail.status}/><Info label="Bước hiện tại" value={detail.currentStepLabel||'Đã kết thúc'}/><Info label="Kết quả gần nhất" value={detail.lastOutcome||'Chưa có'}/><Info label="Người xử lý" value={detail.lastActorName||'SYSTEM'}/><Info label="Thời gian xử lý" value={formatDate(detail.lastActionAt)}/><Info label="Hoàn tất" value={formatDate(detail.completedAt)}/></section><section><h3 className="mb-3 text-xs font-bold uppercase text-slate-500">Lý do / nhận xét</h3><div className={`rounded-xl border p-4 text-sm leading-6 ${detail.lastReason?'border-red-100 bg-red-50 text-red-700':'border-slate-200 bg-slate-50 text-slate-500'}`}>{detail.lastReason||'Không có lý do chi tiết cho dữ liệu lịch sử.'}</div></section><section><h3 className="mb-3 text-xs font-bold uppercase text-slate-500">Dữ liệu dòng</h3><div className="divide-y overflow-hidden rounded-xl border">{Object.entries(detail.fields||{}).map(([key,value])=><div key={key} className="grid grid-cols-[150px_1fr] gap-3 px-4 py-3 text-xs"><span className="break-words font-semibold text-slate-500">{key}</span><Value value={value}/></div>)}</div></section>{detail.systemActions?.length>0&&<section><h3 className="mb-3 text-xs font-bold uppercase text-slate-500">System Action</h3><SystemActionExecutions rows={detail.systemActions}/></section>}</div><footer className="flex items-center justify-between border-t bg-slate-50 px-6 py-4"><button disabled={!previous||loading} onClick={()=>onOpen(previous.rowNumber)} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-semibold disabled:opacity-30"><ChevronLeft size={14}/>Dòng trước</button><button disabled={!next||loading} onClick={()=>onOpen(next.rowNumber)} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-semibold disabled:opacity-30">Dòng sau<ChevronRight size={14}/></button></footer></aside></div>}
function Info({label,value}){return <div><p className="text-[10px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 break-words font-semibold text-slate-700">{value||'—'}</p></div>}
function Value({value}){if(value&&typeof value==='object'&&value.name)return <span className="break-all text-slate-700">📎 {value.name}</span>;if(value&&typeof value==='object')return <pre className="overflow-auto whitespace-pre-wrap break-all rounded bg-slate-50 p-2 text-[10px] text-slate-700">{JSON.stringify(value,null,2)}</pre>;return <span className="whitespace-pre-wrap break-words text-slate-700">{String(value??'—')}</span>}
function SystemActionExecutions({rows}){if(!rows.length)return null;return <section className="mt-7"><p className="mb-3 text-[10px] font-bold uppercase text-gray-400">Connector executions</p><div className="space-y-2">{rows.map(row=><details key={row.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs"><summary className="cursor-pointer font-semibold text-slate-700">{row.stepLabel}{row.batchRowNumber?` · dòng ${row.batchRowNumber}`:''} · <span className={row.status==='SUCCEEDED'?'text-emerald-600':row.status==='FAILED'?'text-red-600':'text-amber-600'}>{row.status}</span></summary><div className="mt-2 space-y-1 text-slate-500"><p>{row.httpMethod} {row.requestUrl}</p><p>Lần thử: {row.attemptCount}/{row.maxAttempts}{row.responseStatus?` · HTTP ${row.responseStatus}`:''}</p>{row.errorMessage&&<p className="text-red-600">{row.errorMessage}</p>}{Object.keys(row.mappedOutputs||{}).length>0&&<pre className="mt-2 overflow-auto rounded bg-white p-2 text-[10px]">{JSON.stringify(row.mappedOutputs,null,2)}</pre>}</div></details>)}</div></section>}
function formatDate(value){return value?new Date(value).toLocaleString('vi-VN'):'—'}
function summarizeValue(value){if(value&&typeof value==='object'&&value.name)return `📎 ${value.name}`;if(value&&typeof value==='object')return JSON.stringify(value);return String(value??'—')}
async function apiError(response){const body=await response.json().catch(()=>null);return body?.message||`HTTP ${response.status}`}
