package com.company.workflowbuilder.controller;
import com.company.workflowbuilder.service.data.DataPipelineService; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.Page; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.util.*;
@RestController @RequiredArgsConstructor public class DataPipelineController {private final DataPipelineService service;private final com.company.workflowbuilder.service.data.BatchRecordMigrationService migration;
 @GetMapping("/api/pipelines") public List<Map<String,Object>>list(){return service.list();}@GetMapping("/api/pipelines/{id}")public Map<String,Object>get(@PathVariable UUID id){return service.getView(id);}@PostMapping("/api/pipelines")public ResponseEntity<Map<String,Object>>create(@RequestBody Map<String,Object>b){return ResponseEntity.status(201).body(service.save(null,b));}@PutMapping("/api/pipelines/{id}")public Map<String,Object>update(@PathVariable UUID id,@RequestBody Map<String,Object>b){return service.save(id,b);}@DeleteMapping("/api/pipelines/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)public void delete(@PathVariable UUID id){service.delete(id);}
 @PostMapping("/api/pipelines/{id}/preview")public Map<String,Object>preview(@PathVariable UUID id){return service.preview(id);}@PostMapping("/api/pipelines/{id}/publish")public Map<String,Object>publish(@PathVariable UUID id){return service.publish(id);}@PostMapping("/api/pipelines/{id}/run")public Map<String,Object>run(@PathVariable UUID id){return service.requestRun(id);}@GetMapping("/api/pipelines/{id}/runs")public List<Map<String,Object>>runs(@PathVariable UUID id){return service.runHistory(id);}@PostMapping(value="/api/pipelines/{id}/files",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)public Map<String,Object>upload(@PathVariable UUID id,@RequestParam String alias,@RequestPart("file")MultipartFile file){return service.upload(id,alias,file);}
 @PostMapping("/api/pipelines/{id}/discover")public Map<String,Object>discover(@PathVariable UUID id,@RequestBody Map<String,Object>body){return service.discover(id,body);}@PostMapping("/api/pipelines/{id}/preview-output")public Map<String,Object>previewOutput(@PathVariable UUID id,@RequestBody Map<String,Object>body){return service.previewOutput(id,body);}
 @PutMapping("/api/pipelines/{id}/schedule")public Map<String,Object>schedule(@PathVariable UUID id,@RequestBody Map<String,Object>b){return service.schedule(id,b);}
 @GetMapping("/api/datasets")public List<Map<String,Object>>datasets(){return service.datasets();}@GetMapping("/api/datasets/{id}/versions/{version}/records")public Page<Map<String,Object>>records(@PathVariable UUID id,@PathVariable int version,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){return service.datasetRecords(id,version,page,size);}
 @PostMapping("/api/workflow-data-bindings")public ResponseEntity<Map<String,Object>>binding(@RequestBody Map<String,Object>b){return ResponseEntity.status(201).body(service.saveBinding(null,b));}@PutMapping("/api/workflow-data-bindings/{id}")public Map<String,Object>bindingUpdate(@PathVariable UUID id,@RequestBody Map<String,Object>b){return service.saveBinding(id,b);}@GetMapping("/api/workflow-data-bindings")public List<Map<String,Object>>bindings(@RequestParam UUID workflowId){return service.bindingList(workflowId);}@PostMapping("/api/workflow-data-bindings/{id}/run")public Map<String,Object>bindingRun(@PathVariable UUID id){return service.triggerBinding(id);}
 @PostMapping("/api/admin/migrations/batch-records")public Map<String,Object>migrateBatchRecords(){return migration.migrate();}
}
